name: Deploy Python Web App to Azure

on:
  [push]

env:
  AZURE_WEBAPP_NAME: test-python-web-app-deploy-github-actions
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project
  PYTHON_VERSION: '3.8'
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}     # set GH repo secret with the publish profile of the web app
 
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check Requirements file exists
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "requirements.txt"

    - name: Install Dependencies
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        
    - name: Install Django
      if: steps.check_files.outputs.files_exists == 'false'
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install django==3.0.3
        
    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.8'    
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
